### ISSUE TITLE
Unify features

### ISSUE THREAD

**Issue by danebell** [clulab/twitter4food#5]
Move RT, age, and gender capabilities to master. Since we already have a gender classifier, either combine these classifications (e.g. by falling back to text classifier if no image classification available) or let there be a switch in the config file.

Make ensemble OverweightClassifier its own class.

**Comment by MihaiSurdeanu** [comment]
@danebell: Good idea.
And also, good idea to keep track of things as issues!
But, before you change anything, can you please tag this version of the code? So we can replicate submission results, if we need to.

**Comment by danebell** [comment]
Finished with [this commit](https://github.com/clulab/twitter4food/commit/511f13a3b25d2fa7cabe43913882bfbcf70a1dc1).
